### ISSUE TITLE
"Davis current" not outputting anything

### ISSUE THREAD

**Issue by ignition-ctrl** [SimonPersson/davis#1]
Hello, saw your post on r/unixporn. Used cargo to install this, and `davis current` is not outputting anything. It only returns two newline characters. MPD is running, ncmpcpp shows me a connection, and `davis queue` shows my queue. 
Using kitty, and tested on urxvt as well.

**Comment by SimonTeixidor** [comment]
Hi! Could you try to run `davis -v current`, to see if we get some more output from the debug logs? Lets read the full metadata of the track you are listening to. Let's also read the full metadata from the current track: `davis read-comments "$(davis -p status | grep '^Song' | cut -d: -f2-)"`, and see what it contains.

**Comment by ignition-ctrl** [comment]
`davis -v current`:
```
No config file found, using default.
Found no host in config file, defaulting to 127.0.0.1.

```
`davis read-comments "$(davis -p status | grep '^Song' | cut -d: -f2-)"` :
```

```
The second one outputs nothing. I ran `davis -p status`, which gave me this.
```
Song:songs/lalalandsuite.mp3
Time:03:56/07:20 (53%)
State:paused
Position:73
Volume:80%
Repeat:on
Random:off
Single:on
Consume:off
```
I also tried compiling it straight from the github repo, no difference. I don't have a lot of metadata on my songs, usually just the title and artist, and I only have around ~100 songs.

**Comment by SimonTeixidor** [comment]
And what is the output of `davis -p read-comments 'songs/lalalandsuite.mp3'`? Would you mind sending me this file by email?

It's possible that it just lacks any metadata. In that case, I guess davis should default to just showing the filename.

**Comment by ignition-ctrl** [comment]
`davis -p read-comments 'songs/lalalandsuite.mp3'` also outputs nothing.
I tried a variety of different songs, `davis current` shows nothing for them while `davis status` shows the correct information. I download my songs from youtube, and tag them with eyeD3. I sent you an email to simon@flaskpost.me with `lalalandsuite.mp3`.

**Comment by ghost** [comment]
I'm having similiar issues, though the only thing I get as output with `davis current` is `Label Universal Music`. `ffprobe` shows the following Metadata of my song, so that can't be the issue: 

    title           : Just Chuckle
    artist          : 高中正義
    track           : 11/14
    album           : The Rainbow Goblins
    disc            : 1/1
    TMED            : CD
    MusicBrainz Release Group Id: bb67af19-2a36-4af7-9b86-78f5ff077991
    TORY            : 1981
    album_artist    : 高中正義
    MusicBrainz Release Track Id: a602e27b-8dfa-4bec-b36c-00561f75611c
    ARTISTS         : 高中正義
    publisher       : Universal Music
    originalyear    : 1981
    TSO2            : Takanaka, Masayoshi
    artist-sort     : Takanaka, Masayoshi
    BARCODE         : 4988005770516
    CATALOGNUMBER   : UPCY-6718
    MusicBrainz Album Type: album
    MusicBrainz Album Status: official
    MusicBrainz Album Release Country: JP
    Acoustid Id     : 746b9a55-bf9a-47e0-9ab1-d5dddff8044e
    MusicBrainz Album Id: 57d05dc9-2a3a-42d3-943b-41305fe949a7
    MusicBrainz Artist Id: facf743e-1231-410d-bdf1-9ba11a6a4f3c
    MusicBrainz Album Artist Id: facf743e-1231-410d-bdf1-9ba11a6a4f3c
    date            : 2013-06-26

**Comment by SimonTeixidor** [comment]
I've pushed a commit to the branch id3-fix, could one of you try that out?

**Comment by ghost** [comment]
`davis current`

`高中正義`
`Thunder Storm`

`Label Universal Music`
which is the Artist, Songtitle and Label.

Well, that now seems to give the desired output.

**Comment by SimonTeixidor** [comment]
Great, thank you. I've pushed a fix to `main` and released a new version on crates.io.

**Comment by ignition-ctrl** [comment]
Yep, works for me now! Thanks
