### ISSUE TITLE
davis albumart returns error

### ISSUE THREAD

**Issue by ImUrX** [SimonPersson/davis#2]
```
No config file found, using default.
Found no host in config file, defaulting to 127.0.0.1.
An error occured when communicating with MPD:
item not found error (`No file exists') at 0
```
does this basically mean that there is no image?

**Comment by SimonTeixidor** [comment]
Yes, that error indicates that there is no image. See the [MPD docs](https://mpd.readthedocs.io/en/latest/protocol.html#the-music-database) for how it fetches albumart. Basically, it requires you to have a file called `cover.png`, `cover.jpg`, `cover.tiff` or `cover.bmp` in the same directory as the music file.
