### ISSUE TITLE
cover art image display options

### ISSUE THREAD

**Issue by pfr-dev** [SimonPersson/davis#3]
Just wondering if you might include the option for use of `w3m-img` or `ueberzug` for displaying the cover art image instead of `picat` ?

**Comment by SimonTeixidor** [comment]
Hi! The use of `picat` is not built in to davis, it's just what I used in the [cover script](https://github.com/SimonPersson/davis/blob/main/subcommands/cover/davis-cover). You could easily modify this script on your own machine for `w3m-img` or `ueberzug`. Or maybe the script can be made to detect which image tool is installed? Either way I'd be happy to accept a PR. w3m-img and ueberzug are X11 only (I think), and I'm on Wayland, so I won't be looking into it myself.

**Comment by pfr-dev** [comment]
ok thanks. The only reason I ask is because `picat` doesn't work with `st`. ~Perhaps I'll seek compatibility with the `picat` devs.~ Ok, I realise you are the `picat` developer also and that it relies on terminal that support sixels. I'm fairly sure there would be a `sixel` patch for `st` :+1:
