### ISSUE TITLE
Package added to AUR

### ISSUE THREAD

**Issue by ghost** [SimonPersson/davis#7]
Hello,

I am creating an issue just to inform you that your application has been added to the AUR, I found it within the [ArchWiki List of Applications](https://wiki.archlinux.org/title/List_of_applications).

I will submit a PR to add it to the README.md :)

Any issues please email me, or comment on the AUR

Good luck with davis,
Polarian

**Comment by ghost** [comment]
Oh here is the link by the way: https://aur.archlinux.org/packages/davis

**Comment by ghost** [comment]
Report issues to: https://onedev.polarian.dev/polarrepo/davis

**Comment by ghost** [comment]
Package available on PolarRepo too: https://onedev.polarian.dev/polarrepo

**Comment by SimonTeixidor** [comment]
Cool! I'd be happy to accept a PR with a link to your package in the README. Perhaps a repology badge would be even better? I just had a look, and apparently there is also a NetBSD package for davis.

**Comment by ghost** [comment]
@SimonPersson I am really sorry, I have been sick over the last week and I completely forgot to solve this.

Expect a PR within 30 mins :)

**Comment by ghost** [comment]
@SimonPersson I notice in main branch, the version is 0.1.1 but there is only a tag for 0.1.0, I can not package properly if you do not tag.

Please could you tag commit f2080f0e2c246f4fa5be48543817f2cd8ab6cc97 as it was when the version was bumped.

Once you have done this, I will bump the AUR package to 0.1.1

If you want later changes included, please tag them and I will bump the package :)

**Comment by ghost** [comment]
Also if you ever need to contact me, feel free to drop me an email polarian@polarian.dev
