### ISSUE TITLE
Out of bounds panic when searching with invalid query string

### ISSUE THREAD

**Issue by Imphall** [SimonPersson/davis#9]
Great project!

While playing with search queries, I managed to trigger a panic when using unescaped quotes. My original query was something similar to the following, note the double quotes; `davis search "(album == "my fav album")"`

It's reproducible using this minimal example;
```
davis search a a a
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', src/cli.rs:257:59
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted (core dumped)
```

I believe the number of `a` characters is import; it needs to be odd and >3. Using even numbers of characters produces a typical MPD error.

I'm not too good with rust, but I think the slices returned by `self.query.chunks(2)` in src/cli.rs:256 can have a length less than 2 if the vector is not perfectly divisible by the chunk size. This causes the out of bound error when trying to access the missing second element on the following line.

I'm using davis version 0.1.2, mpd version 0.23.12, on x86_64 Linux version 6.2.10

**Comment by SimonTeixidor** [comment]
Hi @Imphall! Thanks for the bug report.

I apologise for the delay in getting back to you. I recently moved houses, so I've been quite busy IRL. I've created a PR with a fix. I'm quite sure it fixes the issue, perhaps you are able to try it out as well? If it's good I'll merge that and prepare a new release.
